buildscript {
    ext.kotlin_version = '1.9.22'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

// SOLO FORZAMOS NDK. El SDK se queda en cada plugin.
subprojects { subproject ->
    subproject.plugins.withId('com.android.application') {
        subproject.android {
            ndkVersion "25.1.893793"
        }
    }
    subproject.plugins.withId('com.android.library') {
        subproject.android {
            ndkVersion "25.1.893793"
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
