name: Compilar Contador
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter 3.22.0 sin cache
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.22.0 --depth 1 $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          echo "$HOME/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
          
      - name: Verificar version
        run: |
          flutter --version
          dart --version
          
      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: contador-apk
          path: build/app/outputs/flutter-apk/app-release.apk
