name: Compilar Contador
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Remove preinstalled Flutter
        run: sudo rm -rf /usr/local/bin/flutter /usr/local/bin/dart

      - name: Set up Flutter 3.27.1
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: false

      - name: Check Flutter version
        run: |
          which flutter
          flutter --version

      - run: flutter pub get
      - name: Install Android SDK 35
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Accept licenses  
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - run: flutter build apk --release
      

      - uses: actions/upload-artifact@v4
        with:
          name: contador-apk
          path: build/app/outputs/flutter-apk/app-release.apk
